### ISSUE TITLE
New Element icon

### ISSUE THREAD

**Issue by n-himitsu** [flathub/im.riot.Riot#122]
The .desktop file links to the old Riot icon.

![Screenshot](https://user-images.githubusercontent.com/67550725/88045925-d0388f80-cb3e-11ea-949d-ad655cf9d4bf.png)

**Comment by SISheogorath** [comment]
We use the same icon name because the flatpak app-id didn't change. The icon itself should be replaced on disk, as we rename the icon as part of the build process and have no riot icon available.

Maybe it's a caching issue in your desktop environment that will sort out itself? Because I can't think of a way that we would still ship the old icon, especially since in my local installs as well as on the flathub frontend the icon has been replace on the app page.

**Comment by creepertron95** [comment]
Probably because many linux icon themes did not replace the icon yet. The icon looks like it came from the Papirus icon theme. They already have an Element icon in their theme but, `im.riot.Riot` is still linked to the old Riot icon.

**Comment by n-himitsu** [comment]
> Probably because many linux icon themes did not replace the icon yet. The icon looks like it came from the Papirus icon theme. They already have an Element icon in their theme but, `im.riot.Riot` is still linked to the old Riot icon.

Thanks @creepertron95, changing my icon theme solved the issue. 
I suggest the Flatpak use a different icon name to prevent conflicts, but otherwise this issue can be closed.

**Comment by SISheogorath** [comment]
@n-himitsu The icon name is identical to the flatpak app-id. Therefore if we don't change that, we won't change the icon name. The discussion about changing the id is happening in #114.
