### ISSUE TITLE
Black screen on startup

### ISSUE THREAD

**Issue by alvarlagerlof** [flathub/im.riot.Riot#234]
![image](https://user-images.githubusercontent.com/14835120/141865340-4a1323d5-6955-4e1a-941c-e8c171911746.png)

**Comment by SISheogorath** [comment]
Uhm, that's not what it's supposed to look like 😅 

Can you use the <kbd>alt</kbd> keys to open the top bar or <kbd>ctrl</kbd> + <kbd>shift</kbd> <kbd>i</kbd> to open the dev tools. And then send a matrix rageshake by typing `mxSendRageshake("Blackscreen on startup", true);` to send a bug report. Additional you could provide a screenshot of the errors in the console.

To be quite honest, I have no idea why this could happen. Might be an OOM thing where the wrong process got killed, but otherwise I have no real idea, therefore the rageshake bug report.

**Comment by alvarlagerlof** [comment]
It only happens on wayland. I think it may be due to the lanch options around ozone? Don't think the mxSendRageshake would provide anything useful as the app is interactive behind it.
