### ISSUE TITLE
Can't access to files

### ISSUE THREAD

**Issue by Split7fire** [flathub/im.riot.Riot#33]
When adding files to messages, can't see any file. I think it is related to flatpak permissions.

**Comment by Mikaela** [comment]
It looks like only downloads folder can be accessed by the flatpak by default.

https://github.com/flathub/im.riot.Riot/blob/381b864f75bbc7b465f6bed9fffc9da4ec220f8e/im.riot.Riot.json#L18

If you have specific directories you would like Riot to be allowed to access, you can use something like `flatpak override --user --filesystem=~/Desktop/Screenshots im.riot.Riot` which would allow it to access `~/Desktop/Screenshots` where I store my screenshots and most often need to upload to Riot. (source: https://github.com/flathub/org.telegram.desktop/issues/23#issuecomment-435114564)

**Comment by Split7fire** [comment]
I think that read/write access to home dir is mandatory for such chat application.

**Comment by Mikaela** [comment]
I haven't had issues with just allowing access to my screenshots folder and I think Riot has no reason to access rest of my home directory. Looking at the Telegram issue where I referred to, I think the real issue is probably https://github.com/flatpak/xdg-desktop-portal/issues/99.

**Comment by Split7fire** [comment]
I checked right now and there is no download dir available for me to choose from. Attached image, when I press "Send" button.
![2019-03-03 21-02-51](https://user-images.githubusercontent.com/13453673/53696271-e6359b00-3df7-11e9-979d-51bbc58e6933.png)

**Comment by TingPing** [comment]
The real issue is that Electron doesn't use GtkFileChooserNative yet. There is a patch for it but it needs work, maybe this decade.

**Comment by SISheogorath** [comment]
At the same time we could mention that the Slack flatpak, which is running proprietary software (just saying), has more capabilities (i.e. access the whole home directory). So for now an easy fix would be to allow Riot more access as we do this for other applications as well.

**Comment by SISheogorath** [comment]
This not only breaks influences the upload button, but also drag and drop. Just had the issues that I couldn't send a PDF.

We should definitely consider to allow the entire home directory, even when it's not a great solution.

**Comment by Mikaela** [comment]
If you have to allow access to the entire home directory, could it at least be read-only? I think the option would be `--filesystem=home:ro` http://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access .

**Comment by MightyCreak** [comment]
Drag'n'drop also behaves weirdly when the app desn't have access to the file. The drag'n'drop process works, but fails at the end, saying the file could not be sent (it doesn't mention a file access issue).

I ran this:
```
flatpak override --user --filesystem=home:ro im.riot.Riot
```
And my life is much much better now :wink: 
:+1: I vote up for adding home as a read-only filesystem.

(The perfect behavior would be, like on Android, to ask the user the rights access when the app doesn't have it, but that is more something to do on the Flatpak/DE side).

**Comment by SISheogorath** [comment]
One possible problem that we should take into consideration is that those directories will appear in the save-dialogs but won't be writable. This is more than contra intuitive and bad UX.

**Comment by MightyCreak** [comment]
That is a very good point.

Actually then -- and I know I might sound heretic -- but then why not enable r/w access right on home?

Maybe it would be smarter to set the same restrictions* as if I were to install the app from a repo. IMHO it would be smarter because users would have a better experience out-of-the-box when using Flatpak and, indirectly, Flathub (that is until there is a proper Flatpak API and a proper UI in the DEs to handle rights in a more user-friendly manner). Setting the same rights as in any other "regular" app will certainly create less friction to the users.

_* if access rights are given to `home`, then it's still better than a regular app since it won't be able to access the entire `host`_

**Comment by Erick555** [comment]
@MightyCreak home access gives app ability to read or steal all user secrets, host doesn't give much more. This isn't much different than using app from your distro repos in term of security.

**Comment by MightyCreak** [comment]
Yeah that's the point I'm trying to make actually 😉
Since repo apps already have access to all the host, it would create less friction if the flatpak app has (at least) access to home

**Comment by MightyCreak** [comment]
Indeed... :thinking: 
But I'm afraid that until Flatpak's rights management is easy to use, users will consider it not as good as their distro repo (unless for very special apps where sandboxing is not an issue for the UX). I presume this will be an important problem for Flatpak adoption.

I'm afraid I got no solution to provide here, and that's what scaring me the most for the future of Flatpak :/

**Comment by SISheogorath** [comment]
The solution is the portal implementation on electron side. I already liked a PR above, sadly no one picked up the work which would benefit all electron-based projects in Flatpak. If someone is good at CPP and may previously contributed to electron it would be overly awesome to see that person picking up and complete the work to use portals instead of Filesystem-access.

**Comment by Mikaela** [comment]
Matrix.org/Riot.im infra was recently compromised entirely including package signing keys, so I am again more hesistant about giving Riot or other apps more permissions than they need, so I would stay with having access only to Downloads and my screenshots directory.

According to the attacker one issues making the compromise possible was everyone/everything given more permissions than they needed.

**Comment by MightyCreak** [comment]
@Mikaela It's not exactly the same. The matrix.org server (and only this server) was compromised because of a security issue with Jenkins, unrelated to Matrix ecosystem.

The fact that they had Jenkins and private keys on their production server is indeed a concern, but it is not related to Matrix or Riot code bases.

Anyway, I explained the issue here: as of today, for an average user, apps seem to have issues when they're packaged with Flatpak, while they seem to work well when installed through a regular repository. They feel simply clunkier. Make no mistake, I completely understand the security reasons behind all that, but, until this issue is fixed somehow, I don't foresee a mass adoption to Flatpak since it doesn't make the life easier.

**Comment by Erick555** [comment]
On the other hand if every app will be allowed to bypass the sandbox then there would be no incentive for apps developers to change their code ever. Even if they change the code, removing existing permission will certainly break someone use case, causing regressions which will create pressure for maintainers to keep them forever.

If flatpaks would behave the same way as distro packages then what's the point of using them in first place? Instead of creating solution for desktop app security we would have more of the same problems and need a brand new package format to fix it again. It's much better to educate users about xdg standard and how to use it.

**Comment by Pointedstick** [comment]
Man, this is really annoying. What is the solution to attaching files and drag-and-drop for files not in `~/Downloads`? If the answer is "none" then people are going to install the un-sandboxed distro package instead of the more secure Flatpak packaging to work around this defect, totally defeating the point of the extra security. If security is annoying, people bypass it.

**Comment by MightyCreak** [comment]
@Pointedstick use override permissions as written here: https://github.com/flathub/im.riot.Riot/issues/33#issuecomment-480278848

**Comment by SISheogorath** [comment]
You can also use [flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) to grant access to more filesystem directories if you don't want to use a CLI.

As pointed out in earlier statements. There is no good answer here. If we just open up the home filesystem, then escaping becomes trivial, which means from a security perspective there is no benefit by using flatpak. The alternative would be to share Pictures, Documents, Music and Videos only, but then you run into the same problem when you use a non-standard directory like, lets say, Nextcloud. Also there is no technical reason for Riot to have access to those directories.

To me the answer is the portal: https://github.com/electron/electron/pull/19159

If you want this to be solved, I suggest to help moving this PR forward.

**Comment by MightyCreak** [comment]
I didn't know about flatseal, thank you so much!

**Comment by SISheogorath** [comment]
The problem I have with `home:ro` is something I mentioned in https://github.com/flathub/im.riot.Riot/issues/33#issuecomment-480878208 already. Those directories will show up in every save dialog and the while you can see them, select them and even press save, you won't see any error message but your document won't be saved there either. And that's something I consider even worse than not having access to those directories.

**Comment by MightyCreak** [comment]
Ah indeed... I forgot about this side effect (mostly because I never really download from Riot, and also because the download button actually opens it in my browser).

**Comment by Pointedstick** [comment]
I have basically two options:
- Give Riot ro or rw access to my home directory myself using the aforementioned terminal command
- Stop using the Flatpak version of the app and go back to even less secure distro packaging

Either one fixes the issue for me, but only one of them allows me to keep using the Flatpak packaging. I agree that security is important, but if you break the user experience in the name of security, you have failed, because people will simply disable the security.

**Comment by MightyCreak** [comment]
I got to agree with @Pointedstick here.. most users won't even try to understand Flatpak and will simply go back to their distrib repos, and they'll think Flatpak does not work. When evaluating the pros and cons, it feels to me that, until Electron and Flatpak fixes their issues, it would be better to do like all the other apps and grant rw access to home (it's actually a better setting than most Flatpak apps).

**Comment by SISheogorath** [comment]
Flatpak can not fix the issue of electron not understanding portals. There is literally no way around that, besides mounting more directories. But the whole argument about "We either allow home:rw or people switch back to insecure distro packages" is flawed from the beginning. For one simple reason: With home:rw it's trivial to escape the sandbox and therefore just by doing that flatpak isn't more secure than distro packages anyway.

Using home:ro has the problem mentioned earlier, which from my perspective provides worse UX than not being able to access directories in first place. But hey, that's maybe something Riot can fix? Sounds a bit like an empty catch to me.

And overall I think at least by using the upload button a user is able to figure out, when it only shows the download directory, maybe by putting something in the Download directory it can be uploaded.

**Comment by MightyCreak** [comment]
You're focusing on downloading, but there's also the drag'n'drop. When dnd'ing from somewhere else than Downloads, you get a weird behavior too (if I remember correctly, since I added home:ro a long time ago).

Also, I do believe Flatpak is the future of applications on Linux, and not only because of its sandboxing feature, but also because it is simpler both for the users and for the developers. To me, and maybe that is why we can't find a compromise here, sandboxing is a nice side effect, but if its not possible yet, so be it. If I want security, I'll secure my machine at a higher level anyway (SElinux and firewall for instance).

That's said, I respect your position, don't worry. You're the one maintaining this package in the end.

**Comment by Erick555** [comment]
> Edit: I do think Flatpak is part of the equation here. As for Android applications, it is not impossible to think that, in the future, Flatpak applications will ask you permissions at runtime. Something like "Riot is trying to access your home directory, would you like to allow Riot to access this directory?".

That would be worse than current portal state where files/dirs are accessed only demand without additional questions.

**Comment by MightyCreak** [comment]
> That would be worse than current portal state where files/dirs are accessed only on demand without additional questions.

From what I understand, what I described is exactly what the [Portals wiki](https://github.com/flatpak/flatpak/wiki/Portals) says:
> The implicit expectation of portals is that the user will always be involved in granting or rejecting a portal request, thus most portal APIs will lead to user interaction in the form of dialogs.

**Comment by Erick555** [comment]
That means when user opens file dialog and select `foo` file then `foo` will be accessible to app without any more questions/confirmations. This isn't the same what you described:

> Flatpak applications will ask you permissions at runtime. Something like "Riot is trying to access your home directory, would you like to allow Riot to access this directory?".

**Comment by MightyCreak** [comment]
> most portal APIs will lead to **user interaction** in the form of **dialogs**.

To me it is pretty clear there will be a dialog asking for privileges. Maybe I am misunderstanding, but I find this sentence pretty straightforward IMO.

**Comment by Erick555** [comment]
There won't be any dialog asking for privileges. Try to use any app that use portal (i.e. firefox) and you'll see.

The only dialog you'll see is the one when you choose which file to open but it's almost the same dialog you see without using portal or without using flatpak. The difference is that it will show all your files even without home access and so on. When user chooses some file in that dialog then it will be automatically allowed to use by app. There is no point to additionally ask user if they really want to access file which they explicitly choose just a second before.

**Comment by SISheogorath** [comment]
For all interested in this topic, please try the build from https://github.com/flathub/im.riot.Riot/pull/136 It would be very useful to know if it's running properly for our user-base or not. If this is successful, we no longer need any special filesystem permissions.

**Comment by hdoupe** [comment]
@SISheogorath Thanks for the fix! Would you mind posting a link to directions for testing the patch?

**Comment by SISheogorath** [comment]
@hdoupe You should be able to use the flatpak install instruction form flathubbot. If not I might trigger a new build.

https://github.com/flathub/im.riot.Riot/pull/136#issuecomment-698947024

**Comment by hdoupe** [comment]
Ah, thanks for the link @SISheogorath! I got an error when I tried to run it:

```
$ flatpak install --user https://dl.flathub.org/build-repo/27334/im.riot.Riot.flatpakref
error: Can't load uri https://dl.flathub.org/build-repo/27334/im.riot.Riot.flatpakref: Server returned status 404: Not Found
```

I saw that maybe I needed to add a flathub repo, but that didn't help:

```
$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```

Sorry about this! I'm new to flatpak.

**Comment by salim-b** [comment]
Ehm, I still can't share files from outside the Flatpak sandbox (e.g. from `~/Downloads/`) without manually giving additional permissions (e.g. in Flatseal to `~/:ro`).

I think I have the latest version of the Element Flatpak:

```sh
$ flatpak info im.riot.Riot

Element - Create, share, communicate, chat and call securely, and bridge to
other apps

          ID: im.riot.Riot
         Ref: app/im.riot.Riot/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.7.10
     License: Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 233.5 MB
     Runtime: org.freedesktop.Platform/x86_64/20.08
         Sdk: org.freedesktop.Sdk/x86_64/20.08

      Commit: 9542b17d5bbab3cb31db860220c63fc640d1cf30edd11922085327c0d619cc6a
      Parent: fda9fd67665f06cf783c3a3b04ac0539ae26b8eb9b658df5fb50accff65ef680
     Subject: Update element-desktop_1.7.9_amd64.deb to 1.7.10 (7f30e583)
        Date: 2020-10-22 16:03:43 +0000
```

I'm on Ubuntu 20.04. What am I missing?

**Comment by SISheogorath** [comment]
Re-opening as #136 didn't work out as expected. We'll wait for the new zybak version to become stable.

**Comment by vchernin** [comment]
Thanks to https://github.com/electron/electron/pull/19159, this issue should be fixed with the release of Electron 14. The file chooser XDG desktop portal will be used instead of the traditional file chooser. The portal can choose any file without giving Element entire file system access. 

[Electron 14 is scheduled for release on August 31st 2021](https://www.electronjs.org/docs/tutorial/electron-timelines). It might take some time for Element to update to Electron 14 after it is released (usually they’re pretty quick though).

When that is released we shouldn’t need to grant any file system to Element Flatpak, since the portal makes any file system access redundant. Drag and drop of any file should also work with other Electron 14 and GTK4 apps (I believe the portal hasn’t been backported to GTK 3).

**Comment by colans** [comment]
Until that gets released, where can we actually find our downloaded files?  I searched all of `~/.var/app/im.riot.Riot`, and there weren't in there.

**Comment by vchernin** [comment]
@colans Could you specify what a “downloaded file” is? Most of this thread is about uploading a file or drag and dropping a file to send it. Do you mean if someone sends a picture or something and you try to download it? Because I’m not sure if that’s actually covered by https://github.com/electron/electron/pull/19159.

**Comment by colans** [comment]
@vchernin Yes, exactly.  I receive the file, decrypt it, and download it.  I get a pop-up asking me where to put it so I say, `/tmp`.  Then I go to `/tmp` locally, and it's not there, even though the app is telling me that it is.  Is there actually a way to get into the sandbox to access the files?  Where is it?

**Comment by SISheogorath** [comment]
We are currently only exposing the `xdg-downloads` folder of your filesystem. By default that's probably `~/Downloads`. If you safe a file anywhere else, it'll only survive in the overlay filesystem while Element is running.

**Comment by vchernin** [comment]
@colans could you give an example procedure? I tried to reproduce your issue and I never got a prompt to save a shared file locally in Element. When I clicked the download button all it did was open the file URL in my web browser. Once the web browser is given the file it's out of scope for Element.

I tried with both a webp and a tar.gz file.

<details><summary>Screenshot</summary><br/>

<img src="https://user-images.githubusercontent.com/38842733/122446644-bfafb580-cf57-11eb-926a-083ed305bd10.png" alt="dog and file" width="200"/>

</details>

**Comment by colans** [comment]
> We are currently only exposing the xdg-downloads folder of your filesystem. By default that's probably ~/Downloads. If you safe a file anywhere else, it'll only survive in the overlay filesystem while Element is running.

Ah, yes!  Saving there actually works.  (I normally prefer `/tmp` because it's not persistent.)

> When I clicked the download button all it did was open the file URL in my web browser.

For me, I get the save-file dialog chooser, which defaults to Downloads.  I initially thought this was strange because it doesn't show all of my normal locations and bookmarks on the left like it normally does; I only see a few things:

![Screenshot from 2021-06-17 13-56-05](https://user-images.githubusercontent.com/1258265/122449387-cc420700-cf73-11eb-8f10-cb7c2a588ba7.png)

I'm on Pop!_OS 20.10, which is mostly just Ubuntu 20.10, if that helps.

I would say this is a major UX bug (i.e. why ask me for a location when there's only one option?), but maybe it isn't generally and I'm on an edge case somehow.

**Comment by vchernin** [comment]
In theory your use case (saving files) could be solved by xdg desktop portal like how https://github.com/electron/electron/pull/19159 uses the portal for choosing files. But I don't see an explict mention that PR added support for saving files. So maybe more electron portal integration is needed so saving files also works without needing directory permissions given.

We could also add write-only permissions to more directories until there is better support for saving files with the portal?

**Comment by wioxjk** [comment]
The flathub package should be considered broken until this is not fixed

**Comment by vchernin** [comment]
@colans I researched a bit and it turns out the fix for choosing files (supporting the file chooser portal) also should apply for saving files. So your issue (saving files to /tmp or anywhere else) should be fixed with Electron 14 like how choosing files should be fixed. 

https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.impl.portal.FileChooser

**Comment by vchernin** [comment]
Unfortunately for drag and drop without file system access we will need https://github.com/electron/electron/issues/30650 as well... the FileChooser portal in Electron 14 won't be enough.

**Comment by Peque** [comment]
Cross-referencing https://github.com/vector-im/element-web/issues/18943, for those wanting to track Electron 14 integration. :blush:
