### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Victor239** [flathub/im.riot.Riot#408]
Changelogs can be displayed on Flathub and within distro app updaters, all that's needed is an `.appdata`/[.metainfo.xml](https://docs.flatpak.org/en/latest/conventions.html#appdata-files) file. 

See these examples of another app's [appdata.xml](https://github.com/flathub/io.github.trigg.discover_overlay/blob/master/io.github.trigg.discover_overlay.appdata.xml), and how their changelog is [displayed on Flathub](https://flathub.org/en-GB/apps/io.github.trigg.discover_overlay).

**Comment by SISheogorath** [comment]
Most importantly it needs someone to full these metadata :) We have a metainfo file, but since most of our updates are created by flathub-external-data-checker (f-e-d-c) which doesn't fetch and therefore can't fill the release information, it would require manual work to do this.

For now, I only bother with this for security releases, to add some useful information about these.

Examples:
https://github.com/flathub/im.riot.Riot/pull/407

https://github.com/flathub/im.riot.Riot/blob/1e63e1d0c8c035a1dc0b812d8d26de545d3a0077/im.riot.Riot.metainfo.xml#L32-L221

If you want to help to bring this to reality and make an impact way beyond this specific flatpak, you can work on the issues for f-e-d-c: https://github.com/flathub/flatpak-external-data-checker/issues/222
