### ISSUE TITLE
File open dialog uses the wrong theme

### ISSUE THREAD

**Issue by starcraft66** [flathub/im.riot.Riot#42]
I'm running Fedora 29 with GNOME 3.30.2 and the GTK theme set to Adwaita Dark. When I launch Riot, the Riot window properly uses the theme and the title bar is dark, but when I press the attach file button in a chat and the file open dialog shows up, the dialog incorrectly uses the white Adwaita theme.
![Screenshot from 2019-04-10 11-11-41](https://user-images.githubusercontent.com/1858154/55890858-78605a00-5b81-11e9-8753-4e80e6c1b5b8.png)

**Comment by SISheogorath** [comment]
@starcraft66 It seems like there is no flatpak extension for the Adwaita Dark theme. Usually flatpak detects the used theme, download the extension for the runtime and applies it automatically. But that only works as long as the theme exists as extension. Due to the lack of it, it'll fall back to the runtime default which results in the dialog you see right now.

You have basically 3 options now if you want to stay with flatpak and Adwaita Dark:

1. Accept the current situation and ignore it until someone chooses the options 2 or 3
2. Open an issue at https://github.com/flathub/flathub/issues (or check if there is already one and complain)
3. Step up and take the chance to contribute something to the project. Build an extension for Adwaita Dark. An example for the Arc theme can be found here: https://github.com/flathub/org.gtk.Gtk3theme.Arc :rocket: 

Would love to see option 3 to happen, but even if not, hope that his answers your question ;)

**Comment by TingPing** [comment]
Adwaita-dark is in the runtime thats why its not an extension.

I'm guessing you just didn't properly set the theme: `gsettings get org.gnome.desktop.interface gtk-theme`

**Comment by starcraft66** [comment]
@TingPing Do I need to run this on my host outside the sandbox?
```
[tristan@Helia infrastructure]$ gsettings get org.gnome.desktop.interface gtk-theme
'Adwaita-dark'
```

**Comment by SISheogorath** [comment]
Closing this for now, if the problem still exists, feel free to reopen :)
