### ISSUE TITLE
Should author be set to New Vector Ltd given that it is unofficial?

### ISSUE THREAD

**Issue by aaronraimist** [flathub/im.riot.Riot#87]

**Comment by aaronraimist** [comment]
Related: https://github.com/flathub/linux-store-frontend/issues/146 https://github.com/flathub/linux-store-frontend/issues/48

Maybe there isn't a better field to put this in. Maybe you could say "New Vector Ltd (Unofficial)" or "New Vector Ltd (Community maintained)"

**Comment by TingPing** [comment]
Author and distributor are two different concepts in my mind. As-is its accurate and not misleading. Considering its a 100% redistribution of upstreams binaries I don't even think calling it unofficial is even accurate. Its the binary they release, its just being sandboxed isn't something they support.

**Comment by indolering** [comment]
> Author and distributor are two different concepts in my mind. As-is its accurate and not misleading. Its even a 100% redistribution of the upstream binaries.

I find it very misleading: I am now trusting a random person on Github to not only *not* insert a backdoor into the Riot software but to keep it updated and well maintained.

**Comment by Erick555** [comment]
Unless you download riot binaries directly from vendor site you always trust some random person that delivers it to you.

**Comment by SISheogorath** [comment]
Hint: I'm part of the Riot Package Maintainers, and while it doesn't mean that I'm part of New Vector Ltd, it means we get notified about critical updates and implement changes ahead of time, to deliver new Riot versions in coordination with the official Riot releases.

In that perspective, from a maintaining perspective, we are very well organized also thanks to the initiative taken by New Vector to get me on board.

**Comment by indolering** [comment]
> Unless you download riot binaries directly from vendor site you always trust some random person that delivers it to you.

I've worked on packaging for a cryptocurrency, so I know how the sausage is made :P

> I'm part of the Riot Package Maintainers, and while it doesn't mean that I'm part of New Vector Ltd, it means we get notified about critical updates and implement changes ahead of time, to deliver new Riot versions in coordination with the official Riot releases.

That sounds about as official as it can get to me.

**Comment by ara4n** [comment]
It's really unfortunate that flathub still doesn't have a way to distinguish between the name of the publisher versus the name of the developer.

In this instance, I think that @aaronraimist has a point - given this repo isn't maintained by New Vector staff, we should probably disambiguate and declare it "New Vector Ltd (community maintained)".  The distinction is significant, because New Vector employees are literally under legal contract not to harm the company, and so there's more than just trust to ensure that badness (accidental or otherwise) doesn't creep in.  And Riot is for better or worse a high value target for abuse, and we don't have any way to review/approve package maintenance activity.

In an ideal world, NV might maintain these packages ourselves, but in practice we simply don't have the bandwidth, and we completely depend on generous contributions of time from folks like @SISheogorath to make them available.  But for the sake of accuracy, we should make it clear that they are indeed community maintained.

**Comment by Erick555** [comment]
@ara4n if you look at the [flathub page](https://flathub.org/apps/details/im.riot.Riot) then you can see that _Developer_ and _Publisher_ are separate entities already.

**Comment by TingPing** [comment]
Flathub wants to more prominently expose "official" status on some packages but this is all a discussion for another place.

**Comment by taw00** [comment]
I took a look at another package. In this case, Firefox, shipped by Fedora. I am looking at the appdata.xml file (a file every Linux desktop application ships, in theory). The file can be found here on most linux systems: `/usr/share/metainfo/firefox.appdata.xml`

Mozilla doesn't create this package. The Fedora community does. And in this case, Firefox is important enough that Red Hat pays that community member to maintain that package.

```
  <project_group>Mozilla</project_group>
  <project_license>GPL-3.0+</project_license>
  <developer_name>Mozilla Corporation</developer_name>
  <url type="bugtracker">https://bugzilla.mozilla.org/</url>
  <url type="help">https://support.mozilla.org/</url>

  <url type="homepage">https://www.mozilla.org</url>
  <update_contact>stransky@redhat.com</update_contact>
```

For Riot, I supply an appdata.xml file for the desktop because the project does not. I include it  in the RPM package I build for Riot as a community member. If you install my RPM, it will land here: `/usr/share/metainfo/riot.appdata.xml`

The info I current add is:
```
  <developer_name>New Vector Ltd</developer_name>
  <update_contact>t0dd_at_protonmail.com</update_contact>
  <url type="homepage">https://riot.im</url>
  <project_license>MIT</project_license>
```

I do add this one paragraph to the description to emphasize that it is packaged by the community. But it is largely unneccesary because very nearly ALL packages you install on a linux system are packaged by the community:
```
      <p>Package builder page: https://github.com/taw00/riot-rpm</p>
```

I probably should add bugtracker link and all that, but ... Folks. The upstream needs to be noted, but packages are ASSUMED to be supplied by the community. This is the world of open source.  Most of the packaging that companies like Red Hat or Canonical ship are not maintained by employees of that company. Especially non-critical things like desktop applications. They are maintained by the larger community.

I am only tracking this issue because noting the upstream is important, and I wanted to ensure New Vector Ltd was the correct upstream since the name has changed a bit over the years.

**Comment by Erick555** [comment]
Appdata files are supposed to be handled upstream and to be packaging agnostic - same appdata should be included in flapak, snap, debian or fedora. It's like a product specification. You can buy iphone from applestore or from amazon and its specification will be the same.

**Comment by taw00** [comment]
Nearly all appdata files include contact information for the packager. And the packager is most often not the upstream vendor unless they are an active member of the various communities (most are only tacitly associated). What's "correct" has a lot of nuance, I suppose. I would love it if upstream vendors supplied robust and complete appdata files. It would make my life easier for sure.

**Comment by Erick555** [comment]
> Nearly all appdata files include contact information for the packager.

Examples? Did you mean `update_contact`? Let me quote [appdata spec](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html):

> <update_contact/> #
> 
>     The <update_contact/> tag is an optional tag which can be added to provide an email address distributors can use to contact the project about invalid or incomplete metadata or – in case the specification has changed – about old metadata. It can also be used to ask general questions in case of an update of the component described in the metadata file.
> 
>     The <update_contact/> tag must only be used by distributors. It is not included in the distribution-provided AppStream XML file, and therefore not exposed to the end user via any kind of UI.
> 
>     Upstream authors might decide to add an email address in cleartext, but spam protection using _AT_ is also valid. The value of this tag is generally treated a case-insensitive way.
> 
>     Example:
> 
>     <update_contact>developer_AT_example.com</update_contact>
> 
> 

Above means it's not contact to packager but contact to upstream developer. Some folks on flathub add their own email in case non-existing upstream appdata file as contacting upstream about metadata doesn't make sense in such case.

The distinction between developer/packager make sense but appdata isn't the place for it.

**Comment by taw00** [comment]
"distributors" is not "upstream development". This brewer and distributor.  "Distributors" are those who "distribute" — i.e., those who package and make those packages available. That distributor _may_ be the developer, but often it is not. And that's how I see it used in practice.

That being said, the specs are ... ambiguous and in most cases, poorly articulated anyway. This is a perfect example of that. It discusses "distributors" which is, in most cases, not the upstream developers. And then it discusses the upstream authors in the same breath. Upstream authors of what? The package? The development team?

It doesn't matter. There is a field for the community that represents the development team in appdata. And if you are a member of the community that represents the packaging, ensure your contact information is included as well. Thank you all for your service. :)

**Comment by Erick555** [comment]
> "distributors" is not "upstream development". Think brewer and distributor. "Distributors" are those who "distribute" — i.e., those who package and make those packages available. That distributor may be the developer, but often it is not (maybe Budweiser is the distributor in some locales). And that's how I see it used in practice.

I think you misread what I quoted because it says:

> provide an email address **distributors can use** to **contact the project**

Which means it's an **upstream project email** that **distributors/packager may use for contact** them, **not the distributor/packager email**. There is no place in appadata where you put distributor/packager info which was my point.

**Comment by TingPing** [comment]
I'm just going to close this.

The developer field is just listing the developer and is correct.

Any distinction about who packages this sadly doesn't exist but that is a discussion for the Flathub website largely.

**Comment by taw00** [comment]
@Erick555 ... though closed, for completeness, you are correct! I misread it.

How it is used in practice is all over the place. That being said, the packager really does need to be included. _somewhere_ I do find it odd that they would have a contact field only intended to be used by distributors? Weird. I will have to reach out to one of the packaging teams (I know a few people at RH) and get their opinion for what the "correct" path is. I will do that for my own benefit. We answered the primary question being raised here.

**Comment by taw00** [comment]
After much churning, I have settled on this within my `io.element.element.metainfo.xml` file:
```
<developer_name>Element/New Vector Ltd</developer_name>
  <custom>
      <value       key="package_maintainer">Todd Warner</value>
      <value key="package_maintainer_email">t0dd_AT_protonmail.com</value>
  </custom>
```

And that `Element/New Vector Ltd` will likely be changed to `Element Ltd` ... or something ... someday.
